### ISSUE TITLE
User Story #5 - Task: Admin Privileges

### ISSUE THREAD

**Issue by im-samwong** [PFratt/Co-Operation-soen341project2023#20]
Only admin user should have privileges to access and modify all job postings and profiles.

Should include:

- Some sort of security feature, way to know when admin is logged on.
- Access to all job postings and profiles and logs.
- Ability to modify, delete, or add any user or job postings.
- Should not be able to create an admin user from a frontend user unless they are also admin.

**Comment by im-samwong** [comment]
Perhaps admin can have their own page to manage everything.

**Comment by q1an-w** [comment]
> Perhaps admin can have their own page to manage everything.

Admin can have custom page showing all the info of employers and candidates, redirect could happen at login
