### ISSUE TITLE
Task: Design Candidate Page, Employer Page, Admin Page

### ISSUE THREAD

**Issue by q1an-w** [PFratt/Co-Operation-soen341project2023#30]
this is for the visibility and esthetics of the user pages

**Comment by q1an-w** [comment]
follow a general 
<div className = "container">
    <div className = "wrapper">
       <div className = element">

  </div>
</div>

**Comment by Denis-Oh** [comment]
Pages will follow a light-colored theme. Mostly whites, light-greys, and light-blues.
- Top bar should be light blue (#f4f6fe)
- Main blocks will be (#e7f3ff) or (#87ceeb)
Refer to the Candidate Page
