### ISSUE TITLE
User Story: Employer posts job openings.

### ISSUE THREAD

**Issue by im-samwong** [PFratt/Co-Operation-soen341project2023#4]
User Story; As an employer, I want to create job postings for position openings in my company, as well as be able to search for and view the profiles of potential job candidates, so that I can find the best fit for my open positions.

**Comment by Denis-Oh** [comment]
**TASK LIST:**

- **Creat Job Posting** (Requirements: job title, company name, job description, location, employment type, salary, experience level/other requirements, application deadline, contacts)

- **View Profile** (View Candidate's Information: desired employment type, education level, experience)

**Comment by q1an-w** [comment]
4 points because: 
- api to post jobs and view the ones user has posted (3 points)
- view candidate list (1 point)

**Comment by PFratt** [comment]
Broken down into user stories #73, #82, #83
