### ISSUE TITLE
User Story: Employer can view all candidate profiles.

### ISSUE THREAD

**Issue by im-samwong** [PFratt/Co-Operation-soen341project2023#73]
As an employer, I want to be able to see all candidates' profiles.

2 Story points: 1 for basic outline design and 1 for implementation.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Employer Can View a List of Candidates|
| Quick Description  | The employer must be able to view potential job candidates |
| Prerequisite  | Employer is signed up<br>Employer is logged on<br>At least one candidate has a completed profile |
| Input | Click on "Candidate Browsing" tab of the Employer page|
| Expected Output | A list of suitable candidates is displayed|
| Observed Output | A list of suitable candidates is displayed|
| Verdict| Passed |
| Comments |  |

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Employer Can View Applicants|
| Quick Description  | The employer must be able to view a list of candidates who have applied to their postings|
| Prerequisite  | Employer is signed up<br>Employer is logged on<br>There is an existing job posting<br>There is a candidate who has applied to that job posting|
| Input | Click on "My Applicants" tab of the Employer page<br>Click on the name of the applicant|
| Expected Output | A popup appears with the application status, applicant name, job title, and date |
| Observed Output | A popup appears with the application status, applicant name, job title, and date |
| Verdict| Passed |
| Comments |  |
