### ISSUE TITLE
User Story: Admin can access all user profiles.

### ISSUE THREAD

**Issue by im-samwong** [PFratt/Co-Operation-soen341project2023#74]
As an admin, I want to be able to view all user profiles.

2 Story points: 1 for api, 1 for rendering.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Admin Can View a List of Users|
| Quick Description  | The admin must be able to view all users |
| Prerequisite  | Admin is signed up<br>Admin is logged on|
| Input | Click on the "All Users" tab of the Admin page|
| Expected Output | A list of all users is displayed|
| Observed Output | A list of all users is displayed|
| Verdict| Passed |
| Comments |  |
