### ISSUE TITLE
User Story: Job seeker can apply to job postings.

### ISSUE THREAD

**Issue by im-samwong** [PFratt/Co-Operation-soen341project2023#76]
As a job seeker, I want to be able to apply to job openings.

2 Story points: 1 for api, 1 for implementation.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Candidate Can Apply to Job Postings|
| Quick Description  | Candidates must be able to apply to job postings|
| Prerequisite  | Employer has created a job posting<br>Candidate has a completed profile|
| Input | |
| Expected Output | |
| Observed Output | |
| Verdict| Pending|
| Comments | Waiting on implementation|
