### ISSUE TITLE
User Story: Admin can modify Job Postings

### ISSUE THREAD

**Issue by q1an-w** [PFratt/Co-Operation-soen341project2023#77]
As an admin, I want to be able to view all Job Postings

2 Story points: 1 for api, 1 for rendering.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Admin Can Modify Job Postings|
| Quick Description  | The admin must be able to modify job postings|
| Prerequisite  | Admin is signed up<br>Admin is logged on<br>There is at least one job posting|
| Input | Click on the "All Jobs" tab of the Admin page<br>Click on the job posting that you want to modify<br>Make the desired changes<br>Click "Save Edits"|
| Expected Output | The job posting is updated|
| Observed Output | The job posting is updated|
| Verdict| Passed |
| Comments |  |
