### ISSUE TITLE
User Story: Admin can modify all user profiles.

### ISSUE THREAD

**Issue by q1an-w** [PFratt/Co-Operation-soen341project2023#78]
As an admin, I want to be able to modify all user profiles.

2 Story points: 1 for api, 1 for rendering.

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Admin Can Delete Users|
| Quick Description  | The admin must be able to delete users |
| Prerequisite  | Admin is signed up<br>Admin is logged on<br>There is at least one other user|
| Input | Click on the "All Users" tab of the Admin page<br>Click on the user that you want to delete<br>Click "Remove User"|
| Expected Output | The user is deleted|
| Observed Output | The user is deleted|
| Verdict| Passed |
| Comments |  |
