### ISSUE TITLE
User Story: Employer can manage applications

### ISSUE THREAD

**Issue by q1an-w** [PFratt/Co-Operation-soen341project2023#83]
As an employer, I want to be able to accept, reject and select applicants for interview

2 story points: rest api implementation

2 story points: frontend implementation

**Comment by PFratt** [comment]
|||
| ------------- | ------------- |
| Tested Requirement | Employer Can Manage Applicantions|
| Quick Description  | The employer must be able to manage the applications which candidates have submitted on their job postings|
| Prerequisite  | Employer is signed up<br>Employer is logged on<br>There is an existing job posting<br>There is a candidate who has applied to that job posting|
| Input | Click on "My Applicants" tab of the Employer page<br>Click on the name of the applicant<br>Click on the button corresponding to your desired action|
| Expected Output | The action is performed and the status of the application is updated|
| Observed Output | |
| Verdict| Pending|
| Comments | Waiting on implementation|
